name = "zotaczonehandheld-bazzite"
description = "Bazzite Image für Zotac Zone"
version = "0.0.1"

# --- Systemeinstellungen ---

[customizations]
hostname = "zotac-zone"

[customizations.timezone]
timezone = "Europe/Berlin"

[customizations.locale]
languages = ["de_DE.UTF-8"]
keyboard = "de"

[[customizations.user]]
name = "root"
# Füge hier wieder deinen generierten SHA-512 Hash ein (muss mit $6$ beginnen)
password = "$6$3AhUOpA7vK3Fje9B$OzpNT3D4ZxcACraD/H15MB/.jI3AhuR8vLhEeEk3sQV0cOM8isPXqGzyQbQvJ21l6Ybkv3uPhdCj0wDGegrXv" 

[[customizations.filesystem]]
mountpoint = "/"
minsize = "16 GiB" #

# --- Installer Einstellungen ---

[customizations.installer.kickstart]
contents = """
%post
bootc switch --mutate-in-place --transport registry ghcr.io/zappelfryx/zotaczonehandheld-bazzite:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone",
]
